### ISSUE TITLE
$refがキーのときMarkdownのリンクにダブルクォートが付加されている

### ISSUE THREAD

**Issue by ysato** [bearsunday/BEAR.ApiDoc#28]
https://github.com/bearsunday/BEAR.ApiDoc/blob/f2560c1ecaf5c766b0641b4a1d05bd00f0766cf7/src/MarkdownTemplate.php#L153

![image](https://user-images.githubusercontent.com/56924527/87312781-fcab4500-c55b-11ea-8fec-44d5bee7eb10.png)

**Comment by koriym** [comment]
Fixed #29
